=== Mu2e/otsdaq-mu2e-stm/stm_spack_requirements/stm01/Data_stm_readout/TableInfo.updateots.bk.20250702_115758/TableInfo.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ROOT">
	<xs:complexType>
	<xs:sequence>
		<xs:element name="TABLE">
		<xs:complexType>
			<xs:sequence>
			<xs:element name="VIEW" minOccurs="1" maxOccurs="1">
			<xs:complexType>
				<xs:sequence>
				<xs:element name="COLUMN" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="Type"	     	type="xs:string" />
					<xs:attribute name="Name"	     	type="xs:string" />
					<xs:attribute name="StorageName" 	type="xs:string" />
					<xs:attribute name="DataType"	 	type="xs:string" />
					<xs:attribute name="DefaultValue"	type="xs:string" />
					<xs:attribute name="DataChoices" 	type="xs:string" />
					<xs:attribute name="MinValue"           type="xs:string" />
					<xs:attribute name="MaxValue"           type="xs:string" />
				</xs:complexType>
				</xs:element>
				</xs:sequence>
				<xs:attribute name="Name" 			type="xs:string"/>
				<xs:attribute name="Type" 			type="xs:string"/>
				<xs:attribute name="Description" 	type="xs:string"/>
			</xs:complexType>
			</xs:element>
			</xs:sequence>
			<xs:attribute name="Name" 			type="xs:string"/>
		</xs:complexType>
		</xs:element>
	</xs:sequence>
	</xs:complexType>
	</xs:element>
</xs:schema>

=== Mu2e/otsdaq-mu2e-stm/stm_spack_requirements/stm02/Data_stm_readout/TableInfo.updateots.bk.20241206_103440/CaloMVAFilterTableInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
	<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TableInfo.xsd">
		<TABLE Name="CaloMVAFilterTable">
			<VIEW Name="CALO_MVA_FILTER_TABLE" Type="File,Database,DatabaseTest" Description="No%20description.">
				<COLUMN Type="UID" 	 Name="UID" 	 StorageName="UID" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="ChildLink-CaloMVA ParameterGroup" 	 Name="LinkToCaloMVAFilterParameterTable" 	 StorageName="LINK_TO_CALO_MVA_FILTER_PARAMETER_TABLE" 		DataType="STRING" 		DataChoices="arbitraryBool=0,TriggerParameterTable"/>
				<COLUMN Type="ChildLinkGroupID-CaloMVA ParameterGroup" 	 Name="LinkToCaloMVAFilterParameterGroupID" 	 StorageName="LINK_TO_CALO_MVA_FILTER_PARAMETER_GROUP_ID" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Comment" 	 Name="CommentDescription" 	 StorageName="COMMENT_DESCRIPTION" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Author" 	 Name="Author" 	 StorageName="AUTHOR" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Timestamp" 	 Name="RecordInsertionTime" 	 StorageName="RECORD_INSERTION_TIME" 		DataType="TIMESTAMP WITH TIMEZONE" 		DataChoices=""/>
			</VIEW>
		</TABLE>
	</ROOT>

=== Mu2e/otsdaq-mu2e-stm/stm_spack_requirements/stm01/Data_stm/TableInfo.updateots.bk.20241024_143958/ROCInterfaceTableInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
	<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TableInfo.xsd">
		<TABLE Name="ROCInterfaceTable">
			<VIEW Name="ROC_INTERFACE_TABLE" Type="File,Database,DatabaseTest" Description="This%20table%20describes%20parameters%20associated%20with%20Mu2e%20Readout%20Controller%20(ROC)%20records.%0A%0AOptionally%2C%20it%20can%20associate%20a%20set%20of%20slow%20controls%20channels%20to%20a%20ROC%20through%20the%20field%20'LinkToSlowControlsChannelTable.'">
				<COLUMN Type="UID" 	 Name="UID" 	 StorageName="UID" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="OnOff" 	 Name="Status" 	 StorageName="STATUS" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="GroupID-ROC" 	 Name="ROCGroupID" 	 StorageName="ROC_GROUP_ID" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="FixedChoiceData" 	 Name="ROCInterfacePluginName" 	 StorageName="ROC_INTERFACE_PLUGIN_NAME" 		DataType="STRING" 		DataChoices="arbitraryBool=0,ROCPolarFireCoreInterface,ROCCalorimeterInterface,ROCTrackerInterface,ROCCosmicRayVetoInterface,ROCExtinctionMonitorInterface,ROCStoppingTargetMonitorInterface,ROCDTCHardwareEmulated"/>
				<COLUMN Type="UniqueGroupData" 	 Name="linkID" 	 StorageName="LINK_ID" 		DataType="NUMBER" 		DataChoices="" 		MinValue="0" 		MaxValue="5"/>
				<COLUMN Type="Data" 	 Name="EventWindowDelayOffset" 	 StorageName="EVENT_WINDOW_DELAY_OFFSET" 		DataType="NUMBER" 		DataChoices=""/>
				<COLUMN Type="TrueFalse" 	 Name="EmulateInDTCHardware" 	 StorageName="EMULATE_IN_DTC_HARDWARE" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="ChildLink-ROCParams" 	 Name="ROCTypeLinkTable" 	 StorageName="ROC_TYPE_LINK_TABLE" 		DataType="STRING" 		DataChoices="arbitraryBool=0,NO_LINK,SubsystemCRVParametersTable,SubsystemCalorimeterParametersTable,SubsystemExtinctionMonitorParametersTable,SubsystemSTMParametersTable,SubsystemTrackerParametersTable"/>
				<COLUMN Type="ChildLinkUID-ROCParams" 	 Name="ROCTypeLinkUID" 	 StorageName="ROC_TYPE_LINK_UID" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="ChildLink-SlowControlsChannels" 	 Name="LinkToSlowControlsChannelTable" 	 StorageName="LINK_TO_SLOW_CONTROLS_CHANNEL_TABLE" 		DataType="STRING" 		DataChoices="arbitraryBool=0,NO_LINK,FESlowControlsTable"/>
				<COLUMN Type="ChildLinkGroupID-SlowControlsChannels" 	 Name="LinkToSlowControlsChannelGroupID" 	 StorageName="LINK_TO_SLOW_CONTROLS_CHANNEL_GROUP_ID" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Comment" 	 Name="CommentDescription" 	 StorageName="COMMENT_DESCRIPTION" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Author" 	 Name="Author" 	 StorageName="AUTHOR" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Timestamp" 	 Name="RecordInsertionTime" 	 StorageName="RECORD_INSERTION_TIME" 		DataType="TIMESTAMP WITH TIMEZONE" 		DataChoices=""/>
			</VIEW>
		</TABLE>
	</ROOT>

=== Mu2e/otsdaq-mu2e-stm/stm_spack_requirements/stm02/Data_stm_readout/TableInfo.updateots.bk.20241206_103440/HelixFilterTableInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
	<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TableInfo.xsd">
		<TABLE Name="HelixFilterTable">
			<VIEW Name="HELIX_FILTER_TABLE" Type="File,Database,DatabaseTest" Description="No%20description.">
				<COLUMN Type="UID" 	 Name="UID" 	 StorageName="UID" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="ChildLink-Digi ParameterGroup" 	 Name="LinkToDigiFilterParameterTable" 	 StorageName="LINK_TO_DIGI_FILTER_PARAMETER_TABLE" 		DataType="STRING" 		DataChoices="arbitraryBool=0,TriggerParameterTable"/>
				<COLUMN Type="ChildLinkGroupID-Digi ParameterGroup" 	 Name="LinkToDigiFilterParameterGroupID" 	 StorageName="LINK_TO_DIGI_FILTER_PARAMETER_GROUP_ID" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="ChildLink-TimeCluster ParameterGroup" 	 Name="LinkToTimeClusterFilterParameterTable" 	 StorageName="LINK_TO_TIME_CLUSTER_FILTER_PARAMETER_TABLE" 		DataType="STRING" 		DataChoices="arbitraryBool=0,TriggerParameterTable"/>
				<COLUMN Type="ChildLinkGroupID-TimeCluster ParameterGroup" 	 Name="LinkToTimeClusterFilterParameterGroupID" 	 StorageName="LINK_TO_TIME_CLUSTER_FILTER_PARAMETER_GROUP_ID" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="ChildLink-Helix ParameterGroup" 	 Name="LinkToHelixFilterParameterTable" 	 StorageName="LINK_TO_HELIX_FILTER_PARAMETER_TABLE" 		DataType="STRING" 		DataChoices="arbitraryBool=0,TriggerParameterTable"/>
				<COLUMN Type="ChildLinkGroupID-Helix ParameterGroup" 	 Name="LinkToHelixFilterParameterGroupID" 	 StorageName="LINK_TO_HELIX_FILTER_PARAMETER_GROUP_ID" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Comment" 	 Name="CommentDescription" 	 StorageName="COMMENT_DESCRIPTION" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Author" 	 Name="Author" 	 StorageName="AUTHOR" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Timestamp" 	 Name="RecordInsertionTime" 	 StorageName="RECORD_INSERTION_TIME" 		DataType="TIMESTAMP WITH TIMEZONE" 		DataChoices=""/>
			</VIEW>
		</TABLE>
	</ROOT>

=== Mu2e/otsdaq-mu2e-stm/stm_spack_requirements/daq13/Data_stm/TableInfo/DTCInterfaceTableInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
	<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TableInfo.xsd">
		<TABLE Name="DTCInterfaceTable">
			<VIEW Name="DTC_INTERFACE_TABLE" Type="File,Database,DatabaseTest" Description="Each%20record%20in%20this%20table%20represents%20a%20Data%20Transfer%20Controller%20(DTC)%20front-end%20instance.%20The%20full%20DTC%20User%20Guide%20can%20be%20found%20at%20mu2edocdb%204097.%20%0A%0AThere%20is%20a%20DTC%20table%20schema%20for%20stand-alone%20DTC%2FROC%20development%20in%20otsdaq-mu2e-config%2FCoreTables%2C%20and%20the%20full%20parameter%20DTC%20table%20schema%20in%20otsdaq-mu2e-config%2FCoreTables%2FAdvanced.%20%0A%0A%0AHere%20are%20some%20notes%20on%20particular%20fields%3A%0A%09-%20%3Cb%3EUID%3A%3C%2Fb%3E%0A%3CINDENT%3EThe%20'UID'%20field%20is%20the%20unique%20ID%20for%20the%20DTC%20record.%3C%2FINDENT%3E%0A%09-%20%3Cb%3EEmulatorMode%3A%3C%2Fb%3E%0A%3CINDENT%3EThe%20'EmulatorMode'%20field%2C%20when%20false%2C%20requires%20a%20DTC%20PCIe%20card%20to%20be%20installed%20and%20active%20in%20the%20node%20which%20instantiates%20this%20DTC%20front-end%20interface.%20When%20true%2C%20no%20hardware%20is%20required%20and%20a%20software%20based%20emulation%20is%20activated.%3C%2FINDENT%3E%0A%09-%20%3Cb%3ELocationInChain%3A%3C%2Fb%3E%0A%3CINDENT%3EThe%20'LocationInChain'%20field%20is%20used%20to%20identify%20the%20location%20of%20the%20DTC%20in%20its%20CFO%20timing%20chain.%20Currently%2C%20the%20location%20in%20chain%20is%20not%20used%2C%20but%20it%20was%20in%20the%20past%20and%20may%20be%20in%20the%20future%20to%20assist%20with%20Loopback%20or%20maintaining%20timing%20chain%20lock.%3C%2FINDENT%3E%0A%09-%20%3Cb%3EDeviceIndex%3A%3C%2Fb%3E%0A%3CINDENT%3EThe%20'DeviceIndex'%20field%20identifies%20PCIe%20slot%20device%20index.%20Each%20Mu2e%20device%20(CFO%20or%20DTC)%20is%20assigned%20an%20incrementing%20DMA%20primary%20index.%20For%20example%2C%20if%20there%20are%202%20DTCs%20installed%20in%20a%20node%2C%20one%20will%20have%20index%200%20and%20one%20will%20have%20index%201.%3C%2FINDENT%3E%0A%09-%20%3Cb%3EEmulateCFO%3A%3C%2Fb%3E%0A%3CINDENT%3EThe%20'EmulateCFO'%20field%20is%20a%20flag%20to%20enable%20or%20disable%20internal%20CFO%20emulation%20in%20the%20DTC.%20When%20using%20an%20external%20CFO%2C%20this%20should%20be%20false.%20When%20in%20Mu2e%20Global%20Event%20Building%20Mode%2C%20this%20flag%20is%20ignored%20and%20the%20DTC%20is%20setup%20to%20be%20in%20a%20timing%20chain.%3C%2FINDENT%3E%0A%09-%20%3Cb%3EConfigureClock%3C%2Fb%3E%20%26%20%3Cb%3EJitterAttenuatorInputSource%3A%3C%2Fb%3E%0A%3CINDENT%3EThe%20'ConfigureClock'%20enables%20a%20Jitter%20Attenuator%20(JA)%20reset%20during%20the%20configure%20transition%20based%20on%20the%20'JitterAttenuatorInputSource'%20field.%3C%2FINDENT%3E%0A%09-%20%3Cb%3EEnableROCConfigureStep%3C%2Fb%3E%20%26%20%3Cb%3ELinkToROCGroupTable%3C%2Fb%3E%20%26%20%3Cb%3ELinkToROCGroupID%3C%2Fb%3E%3A%0A%3CINDENT%3EThe%20'EnableROCConfigureStep'%20field%20is%20a%20flag%20to%20enable%20or%20disable%20running%20the%20children%20ROC(s)%20configure%20transition%20code%20based%20on%20the%20ROC%20front-end%20instance(s)%20specified%20by%20the%20'LinkToROCGroupTable'%20and%20the%20'LinkToROCGroupID'%20fields.%200-6%20children%20ROCs%20are%20allowed%20per%20DTC.%3C%2FINDENT%3E%0A%09-%20%3Cb%3EEnableSoftwareDataRequestMode%3A%3C%2Fb%3E%0A%3CINDENT%3EThe%20'EnableSoftwareDataRequestMode'%20field%20is%20a%20flag%20to%20enable%20or%20disable%20Software%20Data%20Request%20Mode.%20When%20false%2C%20automatic%20Data%20Request%20generation%20at%20the%20DTC%20is%20enable.%3C%2FINDENT%3E%0A%09-%20%3Cb%3EEnableSoftwareDataRequestMode%3A%3C%2Fb%3E%0A%3CINDENT%3EThe%20'EnableSoftwareDataRequestMode'%20field%20is%20a%20flag%20to%20enable%20or%20disable%20Software%20Data%20Request%20Mode.%20When%20false%2C%20automatic%20Data%20Request%20generation%20at%20the%20DTC%20is%20enable.%3C%2FINDENT%3E%0A%09-%20%3Cb%3EEventBuilder*%3A%3C%2Fb%3E%0A%3CINDENT%3EThe%20'EventBuilder*'%20fields%20are%20used%20to%20specify%20Hardware%20Event%20Building%20functionality.%20%3Cb%3E'EventBuilderDTCID'%3C%2Fb%3E%20in%20particular%20is%20used%20to%20identify%20DTC%20data%20streams%20in%20artdaq%20data%20analysis%20-%20the%20standard%20calculation%20is%20(nodeIndex%20x%202%20%2B%20DeviceIndex)%2C%20so%20e.g.%20for%20mu2edaq11%2Fdevice-1%20%3D%2011%20x%202%20%2B%201%20%3D%2023.%3C%2FINDENT%3E">
				<COLUMN Type="UID" 	 Name="UID" 	 StorageName="UID" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="TrueFalse" 	 Name="EmulatorMode" 	 StorageName="EMULATOR_MODE" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="LocationInChain" 	 StorageName="LOCATION_IN_CHAIN" 		DataType="NUMBER" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="DeviceIndex" 	 StorageName="DEVICE_INDEX" 		DataType="NUMBER" 		DataChoices=""/>
				<COLUMN Type="YesNo" 	 Name="EmulateCFO" 	 StorageName="EMULATE_CFO" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="YesNo" 	 Name="ConfigureClock" 	 StorageName="CONFIGURE_CLOCK" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="FixedChoiceData" 	 Name="JitterAttenuatorInputSource" 	 StorageName="JITTER_ATTENUATOR_INPUT_SOURCE" 		DataType="STRING" 		DefaultValue="Clock%20from%20CFO" 		DataChoices="arbitraryBool=0,Clock%20from%20RJ45,Timing%20Card%20Selectable%20(SFP%2B%20or%20FPGA)%20Input%20Clock"/>
				<COLUMN Type="YesNo" 	 Name="EnableROCConfigureStep" 	 StorageName="ENABLE_ROC_CONFIGURE_STEP" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="ChildLink-ROC" 	 Name="LinkToROCGroupTable" 	 StorageName="LINK_TO_ROC_GROUP_TABLE" 		DataType="STRING" 		DataChoices="arbitraryBool=0,ROCInterfaceTable,NO_LINK"/>
				<COLUMN Type="ChildLinkGroupID-ROC" 	 Name="LinkToROCGroupID" 	 StorageName="LINK_TO_ROC_GROUP_ID" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="TrueFalse" 	 Name="EnableSoftwareDataRequestMode" 	 StorageName="ENABLE_SOFTWARE_DATA_REQUEST_MODE" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="EventBuilderDTCID" 	 StorageName="EVENT_BUILDER_DTCID" 		DataType="NUMBER" 		DataChoices="" 		MinValue="0" 		MaxValue="255"/>
				<COLUMN Type="Data" 	 Name="EventBuilderMode" 	 StorageName="EVENT_BUILDER_MODE" 		DataType="NUMBER" 		DataChoices="" 		MinValue="0" 		MaxValue="255"/>
				<COLUMN Type="Data" 	 Name="EventBuilderPartitionID" 	 StorageName="EVENT_BUILDER_PARTITION_ID" 		DataType="NUMBER" 		DataChoices="" 		MinValue="0" 		MaxValue="255"/>
				<COLUMN Type="Data" 	 Name="EventBuilderMACIndex" 	 StorageName="EVENT_BUILDER_MAC_INDEX" 		DataType="NUMBER" 		DataChoices="" 		MinValue="0" 		MaxValue="255"/>
				<COLUMN Type="Data" 	 Name="EventBuilderNumBuff" 	 StorageName="EVENT_BUILDER_NUM_BUFF" 		DataType="NUMBER" 		DataChoices="" 		MinValue="0" 		MaxValue="127"/>
				<COLUMN Type="Data" 	 Name="EventBuilderStartNode" 	 StorageName="EVENT_BUILDER_START_NODE" 		DataType="NUMBER" 		DataChoices="" 		MinValue="0" 		MaxValue="127"/>
				<COLUMN Type="Data" 	 Name="EventBuilderNumNodes" 	 StorageName="EVENT_BUILDER_NUM_NODES" 		DataType="NUMBER" 		DataChoices="" 		MinValue="0" 		MaxValue="127"/>
				<COLUMN Type="Comment" 	 Name="CommentDescription" 	 StorageName="COMMENT_DESCRIPTION" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Author" 	 Name="Author" 	 StorageName="AUTHOR" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Timestamp" 	 Name="RecordInsertionTime" 	 StorageName="RECORD_INSERTION_TIME" 		DataType="TIMESTAMP WITH TIMEZONE" 		DataChoices=""/>
			</VIEW>
		</TABLE>
	</ROOT>

=== Mu2e/otsdaq-mu2e-stm/stm_spack_requirements/stm02/Data_stm/TableInfo.updateots.bk.20241024_143958/DigiFilterTableInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
	<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TableInfo.xsd">
		<TABLE Name="DigiFilterTable">
			<VIEW Name="DIGI_FILTER_TABLE" Type="File,Database,DatabaseTest" Description="No%20description.">
				<COLUMN Type="UID" 	 Name="UID" 	 StorageName="UID" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="ChildLink-Digi ParameterGroup" 	 Name="LinkToDigiFilterParameterTable" 	 StorageName="LINK_TO_DIGI_FILTER_PARAMETER_TABLE" 		DataType="STRING" 		DataChoices="arbitraryBool=0,TriggerParameterTable"/>
				<COLUMN Type="ChildLinkGroupID-Digi ParameterGroup" 	 Name="LinkToDigiFilterParameterGroupID" 	 StorageName="LINK_TO_DIGI_FILTER_PARAMETER_GROUP_ID" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Comment" 	 Name="CommentDescription" 	 StorageName="COMMENT_DESCRIPTION" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Author" 	 Name="Author" 	 StorageName="AUTHOR" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Timestamp" 	 Name="RecordInsertionTime" 	 StorageName="RECORD_INSERTION_TIME" 		DataType="TIMESTAMP WITH TIMEZONE" 		DataChoices=""/>
			</VIEW>
		</TABLE>
	</ROOT>

=== Mu2e/otsdaq-mu2e-stm/stm_spack_requirements/stm01/Data_stm/TableInfo.updateots.bk.20241024_143958/Mu2eGlobalsTableInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
	<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TableInfo.xsd">
		<TABLE Name="Mu2eGlobalsTable">
			<VIEW Name="MU2E_GLOBALS_TABLE" Type="File,Database,DatabaseTest" Description="No%20description.">
				<COLUMN Type="UID" 	 Name="UID" 	 StorageName="UID" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="FixedChoiceData" 	 Name="GlobalOperatingMode" 	 StorageName="GLOBAL_OPERATING_MODE" 		DataType="STRING" 		DataChoices="arbitraryBool=0,HardwareDevMode,EventBuildingMode,LoopbackMode"/>
				<COLUMN Type="Data" 	 Name="NumberOfLoopbacks" 	 StorageName="NUMBER_OF_LOOPBACKS" 		DataType="NUMBER" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="NumberOfCAPTANPulses" 	 StorageName="NUMBER_OF_CAPTAN_PULSES" 		DataType="NUMBER" 		DataChoices=""/>
				<COLUMN Type="YesNo" 	 Name="SkipCFOandDTCConfigureSteps" 	 StorageName="SKIP_CF_OAND_DTC_CONFIGURE_STEPS" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Comment" 	 Name="CommentDescription" 	 StorageName="COMMENT_DESCRIPTION" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Author" 	 Name="Author" 	 StorageName="AUTHOR" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Timestamp" 	 Name="RecordInsertionTime" 	 StorageName="RECORD_INSERTION_TIME" 		DataType="TIMESTAMP WITH TIMEZONE" 		DataChoices=""/>
			</VIEW>
		</TABLE>
	</ROOT>

=== Mu2e/otsdaq-mu2e-stm/stm_spack_requirements/stm02/Data_stm_readout/TableInfo.updateots.bk.20241206_103811/XDAQApplicationTableInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
	<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TableInfo.xsd">
		<TABLE Name="XDAQApplicationTable">
			<VIEW Name="XDAQ_APPLICATION_TABLE" Type="File,Database,DatabaseTest" Description="Each%20record%20in%20this%20table%20represents%20a%20XDAQ%20Application.%20A%20group%20of%20XDAQ%20Applications%20form%20a%20XDAQ%20Context.%20In%20otsdaq%2C%20XDAQ%20Applications%20are%20also%20referred%20to%20as%20%22supervisors%2C%22%20and%20each%20supervisor%20has%20some%20specialized%20role%20with%20names%20such%20as%20%22Gateway%20Supervisor%22%20or%20%22Chat%20Supervisor%22%20or%20%22Macro%20Maker%20Supervisor.%22%0A%0AHere%20are%20some%20notes%20on%20particular%20fields%3A%0A%0A%09-%20%3Cb%3EClass%3A%3C%2Fb%3E%0A%3CINDENT%3EThe%20'Class'%20field%20refers%20to%20a%20valid%20ots%20supervisor%20class.%20Suggested%20classes%20are%20provided%20in%20the%20drop-down%20(e.g.%20%22ots%3A%3AGatewaySupervisor%22)%2C%20however%20arbitrary%20editing%20is%20allowed.%0A%0ANote%20that%20%22ots%3A%3AFESupervisor%2C%22%20%22ots%3A%3ADataManagerSupervisor%2C%22%20and%20%22ots%3A%3AARTDAQDataManagerSupervisor%22%20all%20are%20defined%20in%20the%20same%20library%20so%20the%20'Module'%20path%20for%20these%20classes%20should%20be%20%22%24%7BOTSDAQ_LIB%7D%2FlibCoreSupervisors.so.%22%0A%3C%2FINDENT%3E%0A%09-%20%3Cb%3EId%3A%3C%2Fb%3E%0A%3CINDENT%3EThe%20'Id'%20field%20is%20the%20XDAQ%20Application%20ID.%20It%20must%20be%20unique%20within%20an%20application%20group%20(XDAQ%20Context)%20and%20is%20usually%20a%20value%20between%20200%20and%20999.%3C%2FINDENT%3E%0A%09-%20%3Cb%3EInstance%3A%3C%2Fb%3E%0A%3CINDENT%3EThe%20'Instance'%20field%20is%20the%20XDAQ%20Application%20instance.%20The%20value%20is%20usually%201%2C%20however%20arbitrary%20editing%20is%20allowed.%3C%2FINDENT%3E%0A%09-%20%3Cb%3ENetwork%3A%3C%2Fb%3E%0A%3CINDENT%3EThe%20'Network'%20field%20is%20the%20XDAQ%20Application%20network.%20The%20value%20is%20usually%20%22local%2C%22%20however%20arbitrary%20editing%20is%20allowed.%3C%2FINDENT%3E%0A%09-%20%3Cb%3EGroup%3A%3C%2Fb%3E%0A%3CINDENT%3EThe%20'Group'%20field%20is%20the%20XDAQ%20Application%20group.%20The%20value%20is%20usually%20%22daq%2C%22%20however%20arbitrary%20editing%20is%20allowed.%3C%2FINDENT%3E%0A%09-%20%3Cb%3EModule%3A%3C%2Fb%3E%0A%3CINDENT%3EThe%20'Module'%20field%20refers%20to%20the%20path%20of%20the%20class%20library%20which%20corresponds%20to%20the%20selected%20ots%20supervisor%20class.%20Suggested%20library%20paths%20are%20provided%20in%20the%20drop-down%20(e.g.%20%22%24%7BOTSDAQ_LIB%7D%2FlibGatewaySupervisor.so%22)%2C%20however%20arbitrary%20editing%20is%20allowed.%0A%0ANote%20that%20%22ots%3A%3AFESupervisor%2C%22%20%22ots%3A%3ADataManagerSupervisor%2C%22%20and%20%22ots%3A%3AARTDAQDataManagerSupervisor%22%20all%20are%20defined%20in%20the%20same%20library%20so%20the%20'Module'%20path%20for%20these%20classes%20should%20be%20%22%24%7BOTSDAQ_LIB%7D%2FlibCoreSupervisors.so.%22%0A%3C%2FINDENT%3E%0A%09-%20%3Cb%3EConfigurePriority%3A%3C%2Fb%3E%0A%3CINDENT%3EThe%20'ConfigurePriority'%20field%20sets%20the%20priority%2C%20among%20all%20other%20XDAQ%20Applications%2C%20of%20the%20Application%20when%20the%20%3Ci%3Eotsdaq%3C%2Fi%3E%20state%20machine%20is%20Configured.%20The%20priority%20value%20is%20from%201%20to%20255%20inclusive.%200%20(Default)%20is%20translated%20to%20a%20priority%20of%20100.%20%0A%0AFor%20example%2C%20if%20there%20are%20three%20applications%20A%2C%20B%2C%20C%20with%20priority%201%2C%2099%2C%200%20respectively...%20then%20A%20will%20be%20configured%20first%2C%20followed%20by%20C%2C%20and%20then%20B.%09%0A%3C%2FINDENT%3E%0A%09-%20%3Cb%3EStartPriority%2C%20StopPriority%3A%3C%2Fb%3E%0A%3CINDENT%3EThe%20'StartPriority'%20and%20'StopPriority'%20fields%20are%20the%20similar%20to%20the%20'ConfigurePriority'%20field%20except%20for%20they%20set%20the%20priority%20for%20the%20Start%20and%20Stop%20state%20machine%20transitions.%0A%3C%2FINDENT%3E">
				<COLUMN Type="GroupID-0" 	 Name="ApplicationGroupID" 	 StorageName="APPLICATION_GROUP_ID" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="UID" 	 Name="ApplicationUID" 	 StorageName="APPLICATION_UID" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="ChildLink-0" 	 Name="LinkToSupervisorTable" 	 StorageName="LINK_TO_SUPERVISOR_TABLE" 		DataType="STRING" 		DataChoices="arbitraryBool=0,NO_LINK,GatewaySupervisorTable,FESupervisorTable,FEDataManagerSupervisorTable,DataManagerSupervisorTable,ARTDAQSupervisorTable,ARTDAQOnlineMonitorTable,ARTDAQDataLoggerTable,ARTDAQDispatcherTable,ARTDAQBuilderTable,ECLSupervisorTable,SlowControlsDashboardSupervisorTable"/>
				<COLUMN Type="ChildLinkUID-0" 	 Name="LinkToSupervisorUID" 	 StorageName="LINK_TO_SUPERVISOR_UID" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="OnOff" 	 Name="Status" 	 StorageName="STATUS" 		DataType="STRING" 		DefaultValue="1" 		DataChoices=""/>
				<COLUMN Type="FixedChoiceData" 	 Name="Class" 	 StorageName="CLASS" 		DataType="STRING" 		DataChoices="arbitraryBool=1,ots%3A%3AGatewaySupervisor,ots%3A%3AFESupervisor,ots%3A%3ADataManagerSupervisor,ots%3A%3AFEDataManagerSupervisor,ots%3A%3AARTDAQDataManagerSupervisor,ots%3A%3AARTDAQFEDataManagerSupervisor,ots%3A%3AARTDAQSupervisor,ots%3A%3AARTDAQOnlineMonitorSupervisor,ots%3A%3AEventBuilderApp,ots%3A%3ADispatcherApp,ots%3A%3ADataLoggerApp,ots%3A%3AConfigurationGUISupervisor,ots%3A%3AMacroMakerSupervisor,ots%3A%3AVisualSupervisor,ots%3A%3AChatSupervisor,ots%3A%3AConsoleSupervisor,ots%3A%3ALogbookSupervisor,ots%3A%3ASlowControlsDashboardSupervisor,ots%3A%3ACodeEditorSupervisor,ots%3A%3AECLSupervisor"/>
				<COLUMN Type="UniqueData" 	 Name="Id" 	 StorageName="ID" 		DataType="NUMBER" 		DefaultValue="200" 		DataChoices="" 		MinValue="100" 		MaxValue="999"/>
				<COLUMN Type="Data" 	 Name="Instance" 	 StorageName="INSTANCE" 		DataType="NUMBER" 		DefaultValue="1" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="Network" 	 StorageName="NETWORK" 		DataType="STRING" 		DefaultValue="local" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="Group" 	 StorageName="GROUP" 		DataType="STRING" 		DefaultValue="daq" 		DataChoices=""/>
				<COLUMN Type="FixedChoiceData" 	 Name="Module" 	 StorageName="MODULE" 		DataType="STRING" 		DataChoices="arbitraryBool=1,%24%7BOTSDAQ_LIB%7D%2FlibGatewaySupervisor.so,%24%7BOTSDAQ_LIB%7D%2FlibCoreSupervisors.so,%24%7BOTSDAQ_LIB%7D%2FlibEventBuilderApp.so,%24%7BOTSDAQ_UTILITIES_LIB%7D%2FlibChat.so,%24%7BOTSDAQ_UTILITIES_LIB%7D%2FlibConsole.so,%24%7BOTSDAQ_UTILITIES_LIB%7D%2FlibLogbook.so,%24%7BOTSDAQ_UTILITIES_LIB%7D%2FlibECLWriter.so,%24%7BOTSDAQ_UTILITIES_LIB%7D%2FlibVisualization.so,%24%7BOTSDAQ_UTILITIES_LIB%7D%2FlibConfigurationGUI.so,%24%7BOTSDAQ_UTILITIES_LIB%7D%2FlibSlowControlsDashboard.so,%24%7BOTSDAQ_UTILITIES_LIB%7D%2FlibMacroMaker.so,%24%7BOTSDAQ_LIB%7D%2FlibARTDAQSupervisor.so,%24%7BOTSDAQ_LIB%7D%2FlibARTDAQOnlineMonitor.so,%24%7BOTSDAQ_LIB%7D%2FlibDispatcherApp.so,%24%7BOTSDAQ_LIB%7D%2FlibDataLoggerApp.so,%24%7BOTSDAQ_LIB%7D%2FlibCodeEditor.so"/>
				<COLUMN Type="Data" 	 Name="ConfigurePriority" 	 StorageName="CONFIGURE_PRIORITY" 		DataType="NUMBER" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="StartPriority" 	 StorageName="START_PRIORITY" 		DataType="NUMBER" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="StopPriority" 	 StorageName="STOP_PRIORITY" 		DataType="NUMBER" 		DataChoices=""/>
				<COLUMN Type="ChildLink-PropertyGroup" 	 Name="LinkToPropertyTable" 	 StorageName="LINK_TO_PROPERTY_TABLE" 		DataType="STRING" 		DataChoices="arbitraryBool=0,NO_LINK,XDAQApplicationPropertyTable"/>
				<COLUMN Type="ChildLinkGroupID-PropertyGroup" 	 Name="LinkToPropertyGroupID" 	 StorageName="LINK_TO_PROPERTY_GROUP_ID" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Comment" 	 Name="CommentDescription" 	 StorageName="COMMENT_DESCRIPTION" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Author" 	 Name="Author" 	 StorageName="AUTHOR" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Timestamp" 	 Name="RecordInsertionTime" 	 StorageName="RECORD_INSERTION_TIME" 		DataType="TIMESTAMP WITH TIMEZONE" 		DataChoices=""/>
			</VIEW>
		</TABLE>
	</ROOT>
