=== Mu2e/otsdaq-mu2e-stm/stm_spack_requirements/stm01/Data_stm_readout/TableInfo.updateots.bk.20250702_115758/TableInfo.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ROOT">
	<xs:complexType>
	<xs:sequence>
		<xs:element name="TABLE">
		<xs:complexType>
			<xs:sequence>
			<xs:element name="VIEW" minOccurs="1" maxOccurs="1">
			<xs:complexType>
				<xs:sequence>
				<xs:element name="COLUMN" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="Type"	     	type="xs:string" />
					<xs:attribute name="Name"	     	type="xs:string" />
					<xs:attribute name="StorageName" 	type="xs:string" />
					<xs:attribute name="DataType"	 	type="xs:string" />
					<xs:attribute name="DefaultValue"	type="xs:string" />
					<xs:attribute name="DataChoices" 	type="xs:string" />
					<xs:attribute name="MinValue"           type="xs:string" />
					<xs:attribute name="MaxValue"           type="xs:string" />
				</xs:complexType>
				</xs:element>
				</xs:sequence>
				<xs:attribute name="Name" 			type="xs:string"/>
				<xs:attribute name="Type" 			type="xs:string"/>
				<xs:attribute name="Description" 	type="xs:string"/>
			</xs:complexType>
			</xs:element>
			</xs:sequence>
			<xs:attribute name="Name" 			type="xs:string"/>
		</xs:complexType>
		</xs:element>
	</xs:sequence>
	</xs:complexType>
	</xs:element>
</xs:schema>

=== Mu2e/otsdaq-mu2e-stm/stm_spack_requirements/stm01/Data_stm/TableInfo.updateots.bk.20241024_143958/SubsystemTrackerParametersTableInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
	<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TableInfo.xsd">
		<TABLE Name="SubsystemTrackerParametersTable">
			<VIEW Name="SUBSYSTEM_TRACKER_PARAMETERS_TABLE" Type="File,Database,DatabaseTest" Description="No%20description.">
				<COLUMN Type="UID" 	 Name="SubsystemTrackerParametersUID" 	 StorageName="SUBSYSTEM_TRACKER_PARAMETERS_UID" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="NumberParam1" 	 StorageName="NUMBER_PARAM1" 		DataType="NUMBER" 		DataChoices=""/>
				<COLUMN Type="TrueFalse" 	 Name="TrueFalseParam2" 	 StorageName="TRUE_FALSE_PARAM2" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="UniqueData" 	 Name="MustBeUniqueParam3" 	 StorageName="MUST_BE_UNIQUE_PARAM3" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="ChildLink-SubsystemTrackerGroupedParameters" 	 Name="LinkToSubsystemTrackerGroupedParametersTable" 	 StorageName="LINK_TO_SUBSYSTEM_TRACKER_GROUPED_PARAMETERS_TABLE" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="ChildLinkGroupID-SubsystemTrackerGroupedParameters" 	 Name="LinkToSubsystemTrackerGroupedParametersGroupID" 	 StorageName="LINK_TO_SUBSYSTEM_TRACKER_GROUPED_PARAMETERS_GROUP_ID" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Comment" 	 Name="CommentDescription" 	 StorageName="COMMENT_DESCRIPTION" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Author" 	 Name="Author" 	 StorageName="AUTHOR" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Timestamp" 	 Name="RecordInsertionTime" 	 StorageName="RECORD_INSERTION_TIME" 		DataType="TIMESTAMP WITH TIMEZONE" 		DataChoices=""/>
			</VIEW>
		</TABLE>
	</ROOT>

=== Mu2e/otsdaq-mu2e-stm/stm_spack_requirements/stm02/Data_stm/TableInfo.updateots.bk.20241024_143737/FEInterfaceTableInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
	<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TableInfo.xsd">
		<TABLE Name="FEInterfaceTable">
			<VIEW Name="FE_INTERFACE_TABLE" Type="File,Database,DatabaseTest" Description="This%20table%20is%20used%20to%20associate%20a%20plugin%20class%20(and%20its%20table%20specifics)%20with%20a%20front-end%20device.%0A%0AThis%20table%20can%20be%20optionally%20used%20to%20associate%20a%20slow%20control%20table%20with%20a%20front-end.">
				<COLUMN Type="GroupID-FE" 	 Name="FEInterfaceGroupID" 	 StorageName="FE_INTERFACE_GROUP_ID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="UID" 	 Name="FEInterfaceUID" 	 StorageName="FE_INTERFACE_UID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="OnOff" 	 Name="Status" 	 StorageName="STATUS" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="FixedChoiceData" 	 Name="FEInterfacePluginName" 	 StorageName="FE_INTERFACE_PLUGIN_NAME" 		DataType="VARCHAR2" 		DataChoices="arbitraryBool=1,DTCFrontEndInterface,CFOFrontEndInterface,CAPTANSignalGenerator"/>
				<COLUMN Type="ChildLink-0" 	 Name="LinkToFETypeTable" 	 StorageName="LINK_TO_FE_TYPE_TABLE" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="ChildLinkUID-0" 	 Name="LinkToFETypeUID" 	 StorageName="LINK_TO_FE_TYPE_UID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="ChildLink-SlowControlsChannels" 	 Name="LinkToSlowControlsChannelTable" 	 StorageName="LINK_TO_SLOW_CONTROLS_CHANNEL_TABLE" 		DataType="VARCHAR2" 		DataChoices="arbitraryBool=0,NO_LINK,FESlowControlsTable"/>
				<COLUMN Type="ChildLinkGroupID-SlowControlsChannels" 	 Name="LinkToSlowControlsChannelGroupID" 	 StorageName="LINK_TO_SLOW_CONTROLS_CHANNEL_GROUP_ID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Comment" 	 Name="CommentDescription" 	 StorageName="COMMENT_DESCRIPTION" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Author" 	 Name="Author" 	 StorageName="AUTHOR" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Timestamp" 	 Name="RecordInsertionTime" 	 StorageName="RECORD_INSERTION_TIME" 		DataType="TIMESTAMP WITH TIMEZONE" 		DataChoices=""/>
			</VIEW>
		</TABLE>
	</ROOT>

=== Mu2e/otsdaq-mu2e-stm/stm_spack_requirements/stm02/Data_stm/TableInfo.updateots.bk.20241024_143737/TriggerConfigTableInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
	<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TableInfo.xsd">
		<TABLE Name="TriggerConfigTable">
			<VIEW Name="TRIGGER_CONFIG_TABLE" Type="File,Database,DatabaseTest" Description="No%20description.">
				<COLUMN Type="UID" 	 Name="UID" 	 StorageName="UID" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="TriggerDocName" 	 StorageName="TRIGGER_DOC_NAME" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="TriggerConfigTag" 	 StorageName="TRIGGER_CONFIG_TAG" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Comment" 	 Name="CommentDescription" 	 StorageName="COMMENT_DESCRIPTION" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Author" 	 Name="Author" 	 StorageName="AUTHOR" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Timestamp" 	 Name="RecordInsertionTime" 	 StorageName="RECORD_INSERTION_TIME" 		DataType="TIMESTAMP WITH TIMEZONE" 		DataChoices=""/>
			</VIEW>
		</TABLE>
	</ROOT>

=== Mu2e/otsdaq-mu2e-stm/stm_spack_requirements/stm02/Data_stm_readout/TableInfo.updateots.bk.20241206_103440/TriggerPathTableInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
	<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TableInfo.xsd">
		<TABLE Name="TriggerPathTable">
			<VIEW Name="TRIGGER_PATH_TABLE" Type="File,Database,DatabaseTest" Description="No%20description.">
				<COLUMN Type="UID" 	 Name="UID" 	 StorageName="UID" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="GroupID-Trig" 	 Name="PathGroup" 	 StorageName="PATH_GROUP" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="FixedChoiceData" 	 Name="TriggerName" 	 StorageName="TRIGGER_NAME" 		DataType="STRING" 		DataChoices="arbitraryBool=1,tprSeedDeM,tprSeedDeP,cprSeedDeM,cprSeedDeP,tprHelixIPADeM,unbiased,caloMVACE"/>
				<COLUMN Type="FixedChoiceData" 	 Name="TriggerType" 	 StorageName="TRIGGER_TYPE" 		DataType="STRING" 		DataChoices="arbitraryBool=0,TrackSeed,Helix,Unbiased,DigiCount,CaloMVA,CaloMVACE"/>
				<COLUMN Type="Data" 	 Name="PathID" 	 StorageName="PATH_ID" 		DataType="NUMBER" 		DefaultValue="100" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="PrescaleFactor" 	 StorageName="PRESCALE_FACTOR" 		DataType="NUMBER" 		DefaultValue="1" 		DataChoices=""/>
				<COLUMN Type="OnOff" 	 Name="Status" 	 StorageName="STATUS" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="ChildLink-0" 	 Name="LinkToTriggerTable" 	 StorageName="LINK_TO_TRIGGER_TABLE" 		DataType="STRING" 		DataChoices="arbitraryBool=0,TrackSeedFilterTable,HelixFilterTable,DigiFilterTable,UnbiasedFilterTable,CaloMVAFilterTable"/>
				<COLUMN Type="ChildLinkUID-0" 	 Name="LinkToTriggerTableUID" 	 StorageName="LINK_TO_TRIGGER_TABLE_UID" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Comment" 	 Name="CommentDescription" 	 StorageName="COMMENT_DESCRIPTION" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Author" 	 Name="Author" 	 StorageName="AUTHOR" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Timestamp" 	 Name="RecordInsertionTime" 	 StorageName="RECORD_INSERTION_TIME" 		DataType="TIMESTAMP WITH TIMEZONE" 		DataChoices=""/>
			</VIEW>
		</TABLE>
	</ROOT>

=== Mu2e/otsdaq-mu2e-stm/stm_spack_requirements/stm01/Data_stm/TableInfo.updateots.bk.20241024_143958/ARTDAQServicesTableInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
	<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TableInfo.xsd">
		<TABLE Name="ARTDAQServicesTable">
			<VIEW Name="ARTDAQ_SERVICES_TABLE" Type="File,Database,DatabaseTest" Description="No%20description.">
				<COLUMN Type="UID" 	 Name="servicesUID" 	 StorageName="SERVICES_UID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="TrueFalse" 	 Name="sharedMemoryResumeAfterTimeout" 	 StorageName="SHARED_MEMORY_RESUME_AFTER_TIMEOUT" 		DataType="VARCHAR2" 		DataChoices=""/>
        <COLUMN Type="Data" 	 Name="sharedMemoryWaitingTime" 	 StorageName="SHARED_MEMORY_WAITING_TIME" 		DataType="VARCHAR2" 		DataChoices=""/>
        <COLUMN Type="FixedChoiceData" 	 Name="fragmentNamingServiceProvider" 	 StorageName="FRAGMENT_NAMING_SERVICE_PROVIDER" 		DataType="VARCHAR2" 		DataChoices="arbitraryBool=1,OTS,OtsDemo,Mu2e"/>
        <COLUMN Type="ChildLink-daqParameters" 	 Name="ServicesParametersLink" 	 StorageName="SERVICES_PARAMETERS_LINK" 		DataType="VARCHAR2" 		DataChoices="arbitraryBool=0,NO_LINK,ARTDAQDaqParameterTable"/>
				<COLUMN Type="ChildLinkGroupID-daqParameters" 	 Name="ServiceParametersLinkGroupID" 	 StorageName="SERVICE_PARAMETERS_LINK_GROUP_ID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Comment" 	 Name="CommentDescription" 	 StorageName="COMMENT_DESCRIPTION" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Author" 	 Name="Author" 	 StorageName="AUTHOR" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Timestamp" 	 Name="RecordInsertionTime" 	 StorageName="RECORD_INSERTION_TIME" 		DataType="TIMESTAMP WITH TIMEZONE" 		DataChoices=""/>
			</VIEW>
		</TABLE>
	</ROOT>

=== Mu2e/otsdaq-mu2e-stm/stm_spack_requirements/stm02/Data_stm/TableInfo.updateots.bk.20241024_143737/CFOInterfaceTableInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
	<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TableInfo.xsd">
		<TABLE Name="CFOInterfaceTable">
			<VIEW Name="CFO_INTERFACE_TABLE" Type="File,Database,DatabaseTest" Description="No%20description.">
				<COLUMN Type="UID" 	 Name="UID" 	 StorageName="UID" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="DeviceIndex" 	 StorageName="DEVICE_INDEX" 		DataType="NUMBER" 		DataChoices=""/>
				<COLUMN Type="YesNo" 	 Name="ConfigureClock" 	 StorageName="CONFIGURE_CLOCK" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="FixedChoiceData" 	 Name="JitterAttenuatorInputSource" 	 StorageName="JITTER_ATTENUATOR_INPUT_SOURCE" 		DataType="STRING" 	DefaultValue="Local%20oscillator"	DataChoices="arbitraryBool=0,Clock%20from%20RJ45"/>
				<COLUMN Type="Comment" 	 Name="CommentDescription" 	 StorageName="COMMENT_DESCRIPTION" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Author" 	 Name="Author" 	 StorageName="AUTHOR" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Timestamp" 	 Name="RecordInsertionTime" 	 StorageName="RECORD_INSERTION_TIME" 		DataType="TIMESTAMP WITH TIMEZONE" 		DataChoices=""/>
			</VIEW>
		</TABLE>
	</ROOT>

=== Mu2e/otsdaq-mu2e-stm/stm_spack_requirements/stm02/Data_stm_readout/TableInfo.updateots.bk.20241206_103440/DTCInterfaceTableInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
	<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TableInfo.xsd">
		<TABLE Name="DTCInterfaceTable">
			<VIEW Name="DTC_INTERFACE_TABLE" Type="File,Database,DatabaseTest" Description="Modified%20the%20data%20type%20in%20the%20new%20tables">
				<COLUMN Type="UID" 	 Name="UID" 	 StorageName="UID" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="TrueFalse" 	 Name="EmulatorMode" 	 StorageName="EMULATOR_MODE" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="LocationInChain" 	 StorageName="LOCATION_IN_CHAIN" 		DataType="NUMBER" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="DeviceIndex" 	 StorageName="DEVICE_INDEX" 		DataType="NUMBER" 		DataChoices=""/>
				<COLUMN Type="YesNo" 	 Name="EmulateCFO" 	 StorageName="EMULATE_CFO" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="YesNo" 	 Name="ConfigureClock" 	 StorageName="CONFIGURE_CLOCK" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="FixedChoiceData" 	 Name="JitterAttenuatorInputSource" 	 StorageName="JITTER_ATTENUATOR_INPUT_SOURCE" 		DataType="STRING" 		DefaultValue="Clock%20from%20CFO" 		DataChoices="arbitraryBool=0,Clock%20from%20RJ45,Timing%20Card%20Selectable%20(SFP%2B%20or%20FPGA)%20Input%20Clock"/>
				<COLUMN Type="YesNo" 	 Name="EnableROCConfigureStep" 	 StorageName="ENABLE_ROC_CONFIGURE_STEP" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="ChildLink-ROC" 	 Name="LinkToROCGroupTable" 	 StorageName="LINK_TO_ROC_GROUP_TABLE" 		DataType="STRING" 		DataChoices="arbitraryBool=0,ROCInterfaceTable,NO_LINK"/>
				<COLUMN Type="ChildLinkGroupID-ROC" 	 Name="LinkToROCGroupID" 	 StorageName="LINK_TO_ROC_GROUP_ID" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="EventBuilderDTCID" 	 StorageName="EVENT_BUILDER_DTCID" 		DataType="NUMBER" 		DataChoices="" 		MinValue="0" 		MaxValue="255"/>
				<COLUMN Type="Data" 	 Name="EventBuilderMode" 	 StorageName="EVENT_BUILDER_MODE" 		DataType="NUMBER" 		DataChoices="" 		MinValue="0" 		MaxValue="255"/>
				<COLUMN Type="Data" 	 Name="EventBuilderPartitionID" 	 StorageName="EVENT_BUILDER_PARTITION_ID" 		DataType="NUMBER" 		DataChoices="" 		MinValue="0" 		MaxValue="255"/>
				<COLUMN Type="Data" 	 Name="EventBuilderMACIndex" 	 StorageName="EVENT_BUILDER_MAC_INDEX" 		DataType="NUMBER" 		DataChoices="" 		MinValue="0" 		MaxValue="255"/>
				<COLUMN Type="Data" 	 Name="EventBuilderNumBuff" 	 StorageName="EVENT_BUILDER_NUM_BUFF" 		DataType="NUMBER" 		DataChoices="" 		MinValue="0" 		MaxValue="127"/>
				<COLUMN Type="Data" 	 Name="EventBuilderStartNode" 	 StorageName="EVENT_BUILDER_START_NODE" 		DataType="NUMBER" 		DataChoices="" 		MinValue="0" 		MaxValue="127"/>
				<COLUMN Type="Data" 	 Name="EventBuilderNumNodes" 	 StorageName="EVENT_BUILDER_NUM_NODES" 		DataType="NUMBER" 		DataChoices="" 		MinValue="0" 		MaxValue="127"/>
				<COLUMN Type="Comment" 	 Name="CommentDescription" 	 StorageName="COMMENT_DESCRIPTION" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Author" 	 Name="Author" 	 StorageName="AUTHOR" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="Timestamp" 	 Name="RecordInsertionTime" 	 StorageName="RECORD_INSERTION_TIME" 		DataType="TIMESTAMP WITH TIMEZONE" 		DataChoices=""/>
			</VIEW>
		</TABLE>
	</ROOT>

=== Mu2e/otsdaq-mu2e-stm/stm_spack_requirements/stm01/Data_stm/TableInfo/ARTDAQMetricTableInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
	<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TableInfo.xsd">
		<TABLE Name="ARTDAQMetricTable">
			<VIEW Name="ARTDAQ_METRIC_TABLE" Type="File,Database,DatabaseTest" Description="No%20description.">
				<COLUMN Type="GroupID-metrics" 	 Name="metricGroupID" 	 StorageName="METRIC_GROUP_ID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="UID" 	 Name="metricUID" 	 StorageName="METRIC_UID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="OnOff" 	 Name="Status" 	 StorageName="STATUS" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="metricKey" 	 StorageName="METRIC_KEY" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="metricPluginType" 	 StorageName="METRIC_PLUGIN_TYPE" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="metricLevelString" 	 StorageName="METRIC_LEVEL_STRING" 		DataType="VARCHAR2" 		DataChoices=""/>
                <COLUMN Type="TrueFalse" 	 Name="sendSystemMetrics" 	 StorageName="SEND_SYSTEM_METRICS" 		DataType="STRING" 		DataChoices=""/>
                <COLUMN Type="TrueFalse" 	 Name="sendProcessMetrics" 	 StorageName="SEND_PROCESS_METRICS" 		DataType="STRING" 		DataChoices=""/>
				<COLUMN Type="ChildLink-metricParameters" 	 Name="metricParametersLink" 	 StorageName="METRIC_PARAMETERS_LINK" 		DataType="VARCHAR2" 		DataChoices="arbitraryBool=0,NO_LINK,ARTDAQMetricParameterTable"/>
				<COLUMN Type="ChildLinkGroupID-metricParameters" 	 Name="metricParametersLinkGroupID" 	 StorageName="METRIC_PARAMETERS_LINK_GROUP_ID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Comment" 	 Name="CommentDescription" 	 StorageName="COMMENT_DESCRIPTION" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Author" 	 Name="Author" 	 StorageName="AUTHOR" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Timestamp" 	 Name="RecordInsertionTime" 	 StorageName="RECORD_INSERTION_TIME" 		DataType="TIMESTAMP WITH TIMEZONE" 		DataChoices=""/>
			</VIEW>
		</TABLE>
	</ROOT>
